const randomDates = [
    "Flip a coin - whoever wins gets to pick a restaurant for dinner.",
    "Go to the store and purchase 5 items (of any price value) that remind you of your partner.",
    "Sit next to each other, and read seperately.",
    "Go to a restaurant that neither of you have been to before.",
    "In your fanciest attire, dine in at your favorite fast food place.",
    "Backyard camping!",
    "Go rock climbing.",
    "Hit up the arcade!",
    "Turn off all of the lights, play your favorite board game by candlelight.",
    "Karaoke night!",
    "Order/make a food that you have NEVER tried before.",
    "Paint portraits of each other.",
    "Create a time capsule together",
    "Go to a museum",
    "Mini golf time!",
    "Go to a live event, like a concert, comedy night, or something like that!",
    "Early morning coffee and sunrise!",
    "Evening ice cream and sunset!",
    "Go bar hopping! (can be done with thrift stores, coffee shops, game stores, anywhere that can be hopped!)",
    "Go to an escape room.",
    "Go to the zoo!",
    "Get out of town for the night. Book a hotel a few towns over, and find something there. (And try the driving game!)",
    "Ice/Roller Skating",
    "Rent some bikes/scooters downtown and enjoy the weather.",
    "Recreate your favorite childhood fieldtrip!",
    "Take a recreational class. (Pottery, cooking, painting, etc.)",
    "Learn a new card game.",
    "Go on a hike together.",
    "Geocaching",
    "Make matching shirts! (Fabric paint and plain white tee shirts are very cheap!)",
    "Do each other's makeup",
    "Go to a trampoline park!",
    "Pick out some cute new houseplants together.",
    "Go to the drive in.",
    "The Classic: A picnic.",
    "Pillow forts and a movie.",
    "Star gazing!",
    "Dart/Billiards.",
    "Indoor arcade stuff, like bumper cars, laser tag, etc.",
    "Go to a Cat Cafe!",
    "Less of a one-on-one kind of thing, but host a small dinner party for you and some friends!",
    "Screw it, get a tattoo.",
    "Learn a new skill.",
    "The Classic: Order pizza and watch Netflix.",
]
export default randomDates;